server:
  port: 8085
  #阿里云服务器地址和密码
  #jdbc.url=jdbc:mysql://47.98.247.58:3306/dorm?useUnicode=true&amp;characterEncoding=UTF-8
  #jdbc.password=root123
  #私网172.30.156.231  公网47.114.41.52    127.0.0.1

#配置数据库信息

spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  application:
    name: drom-service
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:///dorm?useUnicode=true&amp;characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    hikari: #连接池
      #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），
      #缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      max-lifetime: 28830000
      #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      maximum-pool-size: 9

#扫描的包
mybatis:
  type-aliases-package: com.dorm.mapper
  mapper-locations: src/main/java/com/dorm/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
